- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ftp.zakhem.ke
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    local-dir: ./
    server-dir: /
