name: Deploy to InterServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: vda7000.is.cc
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # 🔥 THIS IS THE KEY FIX
          server-dir: /home/zakhemke/domains/zakhem.ke/public_html/
          
          # 🔥 THIS PREVENTS RANDOM FOLDERS
          dangerous-clean-slate: true 
          d
