- name: Deploy to FTP
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.FTP_SERVER }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    protocol: ftp
    port: 21
    local-dir: ./
    server-dir: /domains/zakhem.ke/public_html/
    dangerous-clean-slate: false  
